% display CAD model and anchor points
function draw_anchor(cls, name)

switch cls
    case 'aeroplane'
        anchor = {'left_elevator_inside', 'left_elevator_outside',...
            'left_wing_back_inside', 'left_wing_back_outside',...
            'left_wing_forward_inside', 'left_wing_forward_outside',...
            'noselanding', 'right_elevator_inside', 'right_elevator_outside',...
            'right_wing_back_inside', 'right_wing_back_outside',...
            'right_wing_forward_inside', 'right_wing_forward_outside',...
            'rudder_lower', 'rudder_upper', 'tail', 'window_center'};
    case 'bed'
        anchor = {'back_left', 'back_right',...
            'frame_upper_left', 'frame_upper_right',...
            'frame_lower_left', 'frame_lower_right',...
            'mattres_upper_left', 'mattres_upper_right',...
            'mattres_lower_left', 'mattres_lower_right'};
    case 'boat'
        anchor = {'head', 'tail_left', 'tail_right', 'tail'};
    case 'bicycle'
        anchor = {'head_center', 'left_back_wheel', 'left_cross_head',...
            'left_cross_seat', 'left_front_wheel',...
            'left_handle', 'left_pedal_center', 'right_back_wheel',...
            'right_cross_head', 'right_cross_seat',...
            'right_front_wheel', 'right_handle', 'right_pedal_center',...
            'seat_back', 'seat_front'};
    case 'bottle'
        anchor = {'body_left', 'body_right',...
            'bottom_left', 'bottom_right',...
            'mouth_left', 'mouth_right'};
    case 'bus'
        anchor = {'body_back_left_lower', 'body_back_left_upper',...
            'body_back_right_lower', 'body_back_right_upper',...
            'body_front_left_upper', 'body_front_right_upper',...
            'left_back_wheel', 'left_front_wheel',...
            'right_back_wheel', 'right_front_wheel',...
            'leftcorner_windshield', 'rightcorner_windshield',...
            'left_headlight', 'right_headlight'};        
    case 'car'
        anchor = {'left_front_wheel', 'left_back_wheel',...
            'right_front_wheel', 'right_back_wheel',...
            'upper_left_windshield', 'lower_left_windshield',...
            'upper_right_windshield', 'lower_right_windshield',...
            'upper_left_rearwindow', 'lower_left_rearwindow',...
            'upper_right_rearwindow', 'lower_right_rearwindow',...
            'left_front_light', 'right_front_light',...
            'left_back_trunk', 'right_back_trunk',...
            'left_window_center', 'right_window_center',...
            'left_window_up', 'right_window_up'};
    case 'cellphone'
        anchor = {'insidescreen_lower_left', 'insidescreen_lower_right',...
            'insidescreen_upper_left', 'insidescreen_upper_right',...
            'lowerkeyboard_lower_left', 'lowerkeyboard_lower_right',...
            'lowerkeyboard_upper_left', 'lowerkeyboard_upper_right',...
            'outsidescreen_lower_left', 'outsidescreen_lower_right',...
            'outsidescreen_upper_left', 'outsidescreen_upper_right',...
            'upperkeyboard_lower_left', 'upperkeyboard_lower_right',...
            'upperkeyboard_upper_left', 'upperkeyboard_upper_right'};
    case 'chair'
        anchor = {'back_upper_left', 'back_upper_right',...
            'seat_upper_left', 'seat_upper_right',...
            'seat_lower_left', 'seat_lower_right',...
            'leg_upper_left', 'leg_upper_right',...
            'leg_lower_left', 'leg_lower_right',...
            'foot_center', 'left_handle_back', 'left_handle_front',...
            'right_handle_back', 'right_handle_front'};
    case 'iron'
        anchor = {'handle_back', 'handle_top', 'back_left', 'back_right', 'tip'};
    case 'motorbike'
        anchor = {'back_seat', 'front_seat', 'head_center', 'headlight_center',...
            'left_back_wheel', 'left_footrest', 'left_front_wheel','left_handle_center',...
            'right_back_wheel', 'right_footrest', 'right_front_wheel', 'right_handle_center'};
    case 'mouse'
        anchor = {'peak', 'head', 'scroll_lower', 'scroll_upper', 'tail'};
    case 'mug'
        anchor = {'bottom_near_handle', 'bottom_opposite_handle',...
            'handle_bottom', 'handle_top', 'top_near_handle', 'top_opposite_handle'};
    case 'shoe'
        anchor = {'back_bottom', 'back_top', 'front_bottom', 'front_line', 'front_top'};
    case 'sofa'
        anchor = {'front_bottom_left', 'front_bottom_right',...
            'seat_bottom_left', 'seat_bottom_right', 'left_bottom_back',...
            'right_bottom_back', 'top_left_corner',  'top_right_corner', ....
            'seat_top_left', 'seat_top_right'};
    case 'stapler'
        anchor = {'back_lower_left', 'back_lower_right', 'back_upper_left',...
            'back_upper_right', 'front_upper_left',...
            'front_upper_right', 'front_bottom_left', 'front_bottom_right'};
    case 'table'
        anchor = {'leg_upper_left', 'leg_upper_right', 'leg_lower_left', 'leg_lower_right',...
            'top_upper_left', 'top_upper_right', 'top_lower_left', 'top_lower_right'};
    case 'toaster'
        anchor = {'leftside_bottom_left', 'leftside_bottom_right',...
            'leftside_top_left', 'leftside_top_right',...
            'rightside_bottom_left', 'rightside_bottom_right',...
            'rightside_top_left', 'rightside_top_right'};
    case 'train'
        anchor = {'head_left_bottom', 'head_left_top', 'head_right_bottom', 'head_right_top', 'head_top',...
            'mid1_left_bottom', 'mid1_left_top', 'mid1_right_bottom', 'mid1_right_top',...
            'mid2_left_bottom', 'mid2_left_top', 'mid2_right_bottom', 'mid2_right_top',...
            'tail_left_bottom', 'tail_left_top', 'tail_right_bottom', 'tail_right_top'};
    case 'tvmonitor'
        anchor = {'front_bottom_left', 'front_bottom_right',...
            'front_top_left', 'front_top_right',...
            'back_bottom_left', 'back_bottom_right',...
            'back_top_left', 'back_top_right'};
    case 'car_aspect'
        anchor = {'left', 'right', 'head', 'tail', 'front', 'back'};
end

filename = sprintf('%s.off', name);
[vertices, faces] = load_off_file(filename);

% display mesh
figure;
trimesh(faces, vertices(:,1), vertices(:,2), vertices(:,3), 'EdgeColor', 'b');
axis equal;
hold on;

% display anchor points
for i = 1:numel(anchor)
    filename = sprintf('%s_%s.off', name, anchor{i});
    if exist(filename) == 0
%         title(sprintf('%s not exist!', anchor{i}));
        continue;
    end
    X = load_off_file(filename);
    if size(X,1) > 1
        X = mean(X);
    end
    plot3(X(1), X(2), X(3), 'ro', 'LineWidth', 10);
end

hold off;